#!/usr/bin/env python
#coding=utf8
import getopt
import sys
from waperagent import *
import time
import threading

goptres = getopt.getopt(sys.argv[1:], 'u:p:i:t:m');
user = '';
passwd = '';
topicid = 0;
text = ';/';
multi = 0;


for opt, arg in goptres[0]:
	if opt in ('-u', ):
		user = arg;
	elif opt in ('-p', ):
		passwd = arg;
	elif opt in ('-i', ):
		topicid = int(arg);
	elif opt in ('-t', ):
		text = arg;
	elif opt in ('-m'):
		multi = 1;

wa = WaperAgent();
wa.init();
try:
	wa.auth(user, passwd);
	sys.stderr.write('Auth ok\n');
except WaperAgentCannotAuth:
	sys.stderr.write('Cannot auth\n');
	sys.exit(1);

i = 0;

def _thread(topicid, text, i):
	global user, passwd, wa;
	wa.auth(user, pawwsd);
	wa.post_to_forum(topicid, text, i);

def multithread():
	global wa, user, passwd, text;
	while 1:
		text += ' ';
		i += 1;
		thread._start_new_thread(_thread, (topicid, text, i));
		time.sleep(1);

def normal():
	global wa, text;
	while 1:
		text += ' ';
		i += 1;
		wa.post_to_forum(topicid, text, i);
		time.sleep(1);

if multi:
	multithread();
else:
	normal();
