#!/usr/bin/env python
#coding=utf8
import getopt
import sys
from waperagent import *
import time
import random

wa = WaperAgent();
wa.init();

goptres = getopt.getopt(sys.argv[1:], 'u:p:i:t:');
user = '';
passwd = '';
forumid = 0;


for opt, arg in goptres[0]:
	if opt in ('-u', ):
		user = arg;
	elif opt in ('-p', ):
		passwd = arg;
	elif opt in ('-i', ):
		forumid = int(arg);

try:
	wa.auth(user, passwd);
	sys.stdout.write('Auth ok\n');
except WaperAgentCannotAuth:
	sys.stderr.write('Cannot auth\n');
	sys.exit(1);

print 'Getting topic list...';
tids = wa.get_all_topics_ids(forumid);

users = [];
for i in tids:
	if i[3] in users: continue
	print i[3];
	users += i[3];
