#!/usr/bin/env python
#coding=utf8
import getopt
import sys
from waperagent import *
import time
import re
import random

goptres = getopt.getopt(sys.argv[1:], 'u:p:f:');
user = '';
passwd = '';
mfiles = '';
forum = '';

for opt, arg in goptres[0]:
    if opt in ('-u', ):
        user = arg;
    elif opt in ('-p', ):
        passwd = arg;
    elif opt in ('-f', ):
        mfile = arg;
    elif opt in ('-r', ):
        forum = arg;

cmd = 'mctg_generator %s'%mfile

wa = WaperAgent();
wa.init();

def proccess_msg(pid, author, text):
    global cmd
    f = os.popen(cmd)
    txt = f.read()
    f.close()
    return txt

def random_post():
    global forum, wa
    ids = wa.get_all_topic_ids(forum)
    topicid = ids[random.randint(0, len(ids)-1)]
    wa.post_to_forum(0, '', '')

try:
    wa.auth(user, passwd);
    sys.stderr.write('Auth ok\n');
except WaperAgentCannotAuth:
    sys.stderr.write('Cannot auth\n');
    sys.exit(1);

while 1:
    if random.randint(0,5) == 3:
        random_post()
    post = None;
    try: post = wa.getnewmsg();
    except: pass
    if post!=None:
        ret = proccess_msg(int(post[0]), post[1], post[2].strip());
        print 'Received msg from '+post[1]+': "'+post[2].strip()+'"';
        print 'Reply is "'+ret+'"'
        wa.answer_in_forum(int(post[0]), '[b]'+post[1]+'[/b], '+ret);
    else: print "No new mesages;/";
     time.sleep(15);
