#!/usr/bin/env python
#coding=utf8
import getopt
import sys
from waperagent import *
import time

wa = WaperAgent();
wa.init();

goptres = getopt.getopt(sys.argv[1:], 'u:p:i:t:x:');
user = '';
passwd = '';
forumid = 0;
text = ';/';
exclude = wa.config.exclude_topics;


for opt, arg in goptres[0]:
    if opt in ('-u', ):
        user = arg;
    elif opt in ('-p', ):
        passwd = arg;
    elif opt in ('-i', ):
        forumid = int(arg);
    elif opt in ('-t', ):
        text = arg;
    elif opt in ('-x'):
        exclude += [int(arg)];

try:
    wa.auth(user, passwd);
    sys.stdout.write('Auth ok\n');
except WaperAgentCannotAuth:
    sys.stderr.write('Cannot auth\n');
    sys.exit(1);

print 'Getting topic list...';
tids = wa.get_all_topics_ids(forumid);
print tids
for i in tids:
    if int(i[0]) in exclude:
        print 'Skipping topic "'+i[1]+'"...';
        continue;
    print 'Posting to "'+i[1]+'"...';
    try: wa.post_to_forum(int(i[0]), text);
    except: pass
