#!/usr/bin/env python
#coding=utf8
import getopt
import sys
from waperagent import *
import time

goptres = getopt.getopt(sys.argv[1:], 'u:p:i:t:');
user = '';
passwd = '';
topicid = 0;
text = ';/';


for opt, arg in goptres[0]:
    if opt in ('-u', ):
        user = arg;
    elif opt in ('-p', ):
        passwd = arg;
    elif opt in ('-i', ):
        topicid = int(arg);
    elif opt in ('-t', ):
        text = arg;

wa = WaperAgent();
wa.init();
try:
    wa.auth(user, passwd);
    sys.stdout.write('Auth ok\n');
except WaperAgentCannotAuth:
    sys.stderr.write('Cannot auth\n');
    sys.exit(1);

try:
    wa.post_to_forum(topicid, text);
except:
    sys.stderr.write("Error.\n");
print'Post sended ok.';
