#!/usr/bin/env python
#coding=utf8
import getopt
import sys
from waperagent import *
import time

wa = WaperAgent();
wa.init();

goptres = getopt.getopt(sys.argv[1:], 'u:p:i:g:');
user = '';
passwd = '';
topic = 0;
generator = 'txt';

for opt, arg in goptres[0]:
    if opt in ('-u', ):
        user = arg;
    elif opt in ('-p', ):
        passwd = arg;
    elif opt in ('-i', ):
        topic = arg;
    elif opt in ('-g', ):
        generator = arg;

try:
    wa.auth(user, passwd);
    sys.stderr.write('Auth ok\n');
except WaperAgentCannotAuth:
    sys.stderr.write('Cannot auth\n');
    sys.exit(1);

info = wa.topic_info(topic)
psts = wa.read_topic(topic);

generator = __import__('savetopic_generator_%s'%generator)
gen = generator.Generator(groupname=info[0], forumname=info[1], topicname=info[2], author=info[3], pages=info[4])
if gen.MODE == 'ONECALL':
    print gen.generate(psts)
elif gen.MODE == 'MANYCALLS':
    print gen.header()
    for p in psts:
        print gen.process_post(p)
    print gen.footer()
else:
    raise ValueError, 'MODE must be \'ONECALL\' or \'MANYCALLS\', not %s'%repr(gen.mode)

