# -*- coding: utf-8 -*-

import re, htmlentitydefs 

def process_bbcode(str):
    h = HTMLParser.HTMLParser()
    str = re.compile('<b>(.*?)</b>', re.DOTALL).sub(r'*\1*', str)
    str = re.compile('<i>(.*?)</i>', re.DOTALL).sub(r'/\1/', str)
    str = re.compile('<s>(.*?)</s>', re.DOTALL).sub(r'-\1-', str)
    str = re.compile('<img.*?alt="(.*?)".*?/>', re.DOTALL).sub(r'\1', str)
    str = re.compile('<br.?/>', re.DOTALL).sub(r'', str)
    str = h.unescape(str)
    return str

class Generator:
    MODE = 'MANYCALLS'
    def __init__(self, **args):
        for argn in args.keys():
            argv = args[argn]
            setattr(self, argn, argv)
    def header(self):
        res = '# -*- coding: utf-8 -*-\n'
        res += '%s -> %s -> %s\n'%(self.groupname, self.forumname, self.topicname)
        return res
    def footer(self): 
        return '\n# Generated by waperagent -> http://github.com/startapp/waperagent/'
    def process_post(self, post):
        res = '<%s> [%s] %s:\n'%(post[0].decode('utf-8'), post[2].decode('utf-8'), post[1].decode('utf-8'))
        res += process_bbcode(post[3].decode('utf-8').strip())
        res += '\n%s\n'%('='*16)
        return res 
